# Generated by Django 4.1.7 on 2023-04-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True, verbose_name='addressname')),
                ('phone', models.BigIntegerField(null=True, verbose_name='mobileno')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.PositiveIntegerField(null=True)),
                ('books', models.PositiveIntegerField(null=True)),
                ('uniforms', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='exphist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.PositiveIntegerField(null=True)),
                ('rec', models.CharField(max_length=801, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.PositiveIntegerField(null=True)),
                ('books', models.PositiveIntegerField(null=True)),
                ('uniforms', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('sclass', models.PositiveSmallIntegerField(null=True)),
                ('familyincome', models.PositiveIntegerField(null=True)),
                ('moneyneeded', models.PositiveIntegerField(null=True)),
                ('books', models.BooleanField(default=False, null=True)),
                ('uniform', models.BooleanField(default=False, null=True)),
                ('performance', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=7, null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='totalmoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.PositiveIntegerField(null=True, verbose_name='money')),
            ],
        ),
        migrations.CreateModel(
            name='pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveBigIntegerField(null=True, verbose_name='paisa')),
                ('status', models.BooleanField(null=True)),
                ('ubstatus', models.BooleanField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('lastpaid', models.DateTimeField(null=True)),
                ('frequency', models.CharField(max_length=120, null=True)),
                ('books', models.PositiveSmallIntegerField(null=True)),
                ('uniform', models.PositiveSmallIntegerField(null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.donor')),
            ],
        ),
    ]
