# Generated by Django 4.1.7 on 2023-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(null=True, verbose_name='addressname'),
        ),
        migrations.AddField(
            model_name='donor',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, verbose_name='emailid'),
        ),
        migrations.AddField(
            model_name='donor',
            name='firstname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='lastname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.BigIntegerField(null=True, verbose_name='mobileno'),
        ),
    ]
