# Generated by Django 4.1 on 2023-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
