# Generated by Django 4.1.7 on 2023-04-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimations',
            name='books',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estimations',
            name='sclass',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estimations',
            name='uniforms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='exp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exphist',
            name='expe',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='books',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sclass',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='uniforms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='familyincome',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='moneyneeded',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='totalmoney',
            name='Sum',
            field=models.PositiveIntegerField(null=True, verbose_name='money'),
        ),
    ]
