# Generated by Django 4.1.7 on 2023-03-31 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.IntegerField(null=True)),
                ('books', models.IntegerField(null=True)),
                ('uniforms', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.IntegerField(null=True)),
                ('books', models.IntegerField(null=True)),
                ('uniforms', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('sclass', models.SmallIntegerField(null=True)),
                ('familyincome', models.IntegerField(null=True)),
                ('moneyneeded', models.IntegerField(null=True)),
                ('books', models.BooleanField(default=False, null=True)),
                ('uniform', models.BooleanField(default=False, null=True)),
                ('performance', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='totalmoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.IntegerField(null=True, verbose_name='money')),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(null=True, verbose_name='addressname'),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.BigIntegerField(null=True, verbose_name='mobileno'),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveBigIntegerField(null=True, verbose_name='paisa')),
                ('status', models.BooleanField(null=True)),
                ('books', models.PositiveSmallIntegerField(null=True)),
                ('uniform', models.PositiveSmallIntegerField(null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.donor')),
            ],
        ),
    ]
