# Generated by Django 4.1.7 on 2023-03-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_remove_donor_name_donor_address_donor_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveBigIntegerField(null=True, verbose_name='paisa')),
                ('status', models.BooleanField(null=True)),
                ('books', models.PositiveSmallIntegerField(null=True)),
                ('uniform', models.PositiveSmallIntegerField(null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.donor')),
            ],
        ),
    ]
