# Generated by Django 4.1.7 on 2023-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_estimations_inventory_student_totalmoney_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='exphist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.IntegerField(null=True)),
                ('rec', models.CharField(max_length=801, null=True)),
            ],
        ),
    ]
