# Generated by Django 4.1.7 on 2023-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='frequency',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='lastpaid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
