# Generated by Django 4.1.7 on 2023-03-26 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGO', '0003_pledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('sclass', models.SmallIntegerField(null=True)),
                ('familyincome', models.IntegerField(null=True)),
                ('moneyneeded', models.IntegerField(null=True)),
                ('books', models.BooleanField(null=True)),
                ('uniform', models.BooleanField(null=True)),
                ('performance', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pledge',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
