# Generated by Django 4.1.7 on 2023-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_student_alter_pledge_donor_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='books',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='money',
            field=models.IntegerField(null=True, verbose_name='Money'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='uniform',
            field=models.IntegerField(null=True),
        ),
    ]
