# Generated by Django 4.1.7 on 2023-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_student_alter_pledge_donor_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.SmallIntegerField(null=True)),
                ('books', models.PositiveIntegerField(null=True)),
                ('uniform', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
