# Generated by Django 4.1.7 on 2023-03-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_alter_pledge_books_alter_pledge_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uniform',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
