# Generated by Django 4.1.7 on 2023-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_estimations'),
    ]

    operations = [
        migrations.CreateModel(
            name='actual_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.SmallIntegerField(null=True)),
                ('books', models.IntegerField(null=True)),
                ('uniform', models.IntegerField(null=True)),
            ],
        ),
    ]
