# Generated by Django 4.1.7 on 2023-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0006_alter_student_books_alter_student_uniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='did',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='donor',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
