# Generated by Django 4.1.7 on 2023-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0009_remove_pledge_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalmoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.BigIntegerField(null=True, verbose_name='money')),
            ],
        ),
    ]
