# Generated by Django 4.1.7 on 2023-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0010_totalmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmoney',
            name='Sum',
            field=models.IntegerField(null=True, verbose_name='money'),
        ),
    ]
