# Generated by Django 4.1.7 on 2023-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0011_alter_totalmoney_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclass', models.IntegerField(null=True)),
                ('books', models.IntegerField(null=True)),
                ('uniforms', models.IntegerField(null=True)),
            ],
        ),
    ]
